testing retrying build with ssh first job exports a sample environment variable SSH_TEST_VAR second job restarts first job as ssh build, fetches build and ssh host and port and then executes remote command to echo SSH_TEST_VAR. test passes if value of SSH_TEST_VAR is as expected and there are no errors throughout

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -31,6 +31,10 @@ workspaces_defaults: &workspaces_defaults
   docker: [{image: 'circleci/node:latest'}]
   working_directory: ~/foo/bar
 
+ssh_defaults: &ssh_defaults
+  docker: [{image: 'circleci/node:latest'}]
+  working_directory: ~/foo/bar
+
 jobs:
   # resource class jobs
   small: # 1 vCPU, 2GB RAM
@@ -185,6 +189,75 @@ jobs:
       - store_test_results:
           path: test-results
 
+  start_ssh_job:
+    <<: *ssh_defaults
+    steps:
+      - run: |
+          echo 'SSH_TEST_VAR="success"' >> $BASH_ENV
+          source $BASH_ENV
+          mkdir -p build
+          echo "$CIRCLE_BUILD_NUM" > ./build/number
+      - persist_to_workspace:
+          root: .
+          paths:
+            - build
+
+  try_ssh:
+    <<: *ssh_defaults
+    steps:
+      - attach_workspace:
+           at: ./attached
+      - run: |
+          BUILD_NUMBER="$(cat ./attached/build/number)"
+          if [[ -z "${BUILD_NUMBER}" ]]; then
+            echo "build number not set"
+            exit 1
+          fi
+          BASE_URL="$(cut -d/ -f1-3 <<< "$CIRCLE_BUILD_URL")"
+          VCS_TYPE="github"
+          URL="$BASE_URL/api/v1.1/project/$VCS_TYPE/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$BUILD_NUMBER/ssh?circle-token=$CIRCLE_TOKEN"
+          I=0
+          LIMIT=10
+          TIMEOUT=5
+          while [[ $I -lt $LIMIT ]]; do
+            SSH_BUILD_NUM="$(curl -s -k -XPOST "$URL" | jq -r '.build_num')"
+            echo "ssh build num: '$SSH_BUILD_NUM'"
+            if [[ -z "$SSH_BUILD_NUM" ]] || [ "$SSH_BUILD_NUM" = "null" ]; then
+              I=$((I+1))
+              sleep $TIMEOUT
+            else
+              break
+            fi
+          done
+          if [[ -z "$SSH_BUILD_NUM" ]] || [ "$SSH_BUILD_NUM" = "null" ]; then
+            echo "--Error retrying build ${BUILD_NUMBER} with SSH"
+            exit 1
+          fi
+          BUILD_URL="$BASE_URL/api/v1.1/project/$VCS_TYPE/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$SSH_BUILD_NUM?circle-token=$CIRCLE_TOKEN"
+          I=0
+          while [[ $I -lt $LIMIT ]]; do
+            SSH_HOST_PORT="$(curl -s -k "$BUILD_URL" | jq -r '.picard.ssh_servers[0].server')"
+            echo "ssh host: '$SSH_HOST_PORT'"
+            if [[ -z "$SSH_HOST_PORT" ]] || [ "$SSH_HOST_PORT" = "null" ]; then
+              I=$((I+1))
+              sleep $TIMEOUT
+            else
+              break
+            fi
+          done
+          if [[ -z "$SSH_HOST_PORT" ]] || [ "$SSH_HOST_PORT" = "null" ]; then
+            echo "--Error fetching build ${SSH_BUILD_NUM} or build does not contain SSH information"
+            exit 1
+          fi
+          SSH_HOST="$(cut -d':' -f1 <<< "$SSH_HOST_PORT")"
+          SSH_PORT="$(cut -d':' -f2 <<< "$SSH_HOST_PORT")"
+          SSH_TEST_VAR="$(ssh -o StrictHostKeyChecking=no -p ${SSH_PORT} ${SSH_HOST} 'echo $SSH_TEST_VAR')"
+          EXPECT="success"
+          if [ "${SSH_TEST_VAR}" != "${EXPECT}" ]; then
+            echo "--Got '${SSH_TEST_VAR}', Expected '${EXPECT}'"
+            exit 1
+          fi
+          echo "--SSH Test Successful"
 workflows:
   version: 2
   resource_class_jobs:
@@ -214,3 +287,7 @@ workflows:
           requires:
             - write_workspace
       - artifacts_test_results
+      - start_ssh_job
+      - try_ssh:
+          requires:
+            - start_ssh_job
